# Generated by Django 6.0.2 on 2026-03-20 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='background',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='character',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
