# Generated by Django 6.0.2 on 2026-03-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_message_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=10000),
        ),
    ]
