# Generated by Django 6.0.2 on 2026-03-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_message_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
