# Generated by Django 6.0.2 on 2026-03-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_systemprompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompts',
            new_name='prompt',
        ),
    ]
